# Auto-generated by /home/evsio0n/src/edk2sdm/Sdm835/../edk2/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/home/evsio0n/src/edk2sdm/Sdm835/workspace
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/home/evsio0n/src/edk2sdm/Sdm835/../edk2/BaseTools
fi
if [ -e /home/evsio0n/src/edk2sdm/Sdm835/../edk2/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//home/evsio0n/src/edk2sdm/Sdm835/../edk2/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/home/evsio0n/src/edk2sdm/Sdm835/../edk2/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
